sudo: false
language: ruby
before_install: gem install bundler -v 1.15.4
bundler_args: "--without development"
script:
  - cat Gemfile.lock
  - bundle list
  - COVERAGE=yes bundle exec rake $CHECK
cache: bundler
matrix:
  include:
    - rvm: 2.4.1
      env: PUPPET_GEM_VERSION='~> 5'
    - rvm: 2.4.1
      env: CHECK=rubocop
    - rvm: 2.4.1
      env: PUPPET_GEM_VERSION='~> 5.0.0'
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION='~> 4'
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION='~> 4.9.0'
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION='~> 4.8.0'
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION='~> 4.7.0'
    - rvm: 2.4.1
      env: CHECK=license_finder
      bundler_args: ""
