# version: 1.0.{build}-{branch}

environment:
  matrix:
    - RUBY_VERSION: 24-x64
    - RUBY_VERSION: 21-x64

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
  - SET LOG_SPEC_ORDER=true
  - bundle install --jobs 4 --retry 2 --without development

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - type Gemfile.lock

test_script:
  - bundle exec rake

# Uncomment this block to enable RDP access to the AppVeyor test instance for
# debugging purposes.
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
